config/routes.rb
Rails.application.routes.draw do
  get "/admin", to: "admin#index"
  namespace :admin do
    resources :jobs
    resources :companies
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "page#index"
  get "/companies", to: "page#companies"
  get "/companies/:id", to: "page#company", as: "company"
  get "/jobs", to: "page#jobs"
  get "/jobs/:id", to: "page#job", as: "job"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/company.rb
class Admin::Company < ApplicationRecord
  has_many :jobs, :foreign_key => "admin_company_id"
  scope :enabled, -> { where( :enabled => true ) }
end

app/models/admin/job.rb
class Admin::Job < ApplicationRecord
  belongs_to :company, :class_name => "Admin::Company", :foreign_key => "admin_company_id"
  scope :enabled, -> { where(:enabled => true) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :set_admin_company, only: [:show, :edit, :update, :destroy]

  # GET /admin/companies
  # GET /admin/companies.json
  def index
    @admin_companies = Admin::Company.all
  end

  # GET /admin/companies/1
  # GET /admin/companies/1.json
  def show
  end

  # GET /admin/companies/new
  def new
    @admin_company = Admin::Company.new
  end

  # GET /admin/companies/1/edit
  def edit
  end

  # POST /admin/companies
  # POST /admin/companies.json
  def create
    @admin_company = Admin::Company.new(admin_company_params)

    respond_to do |format|
      if @admin_company.save
        format.html { redirect_to @admin_company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @admin_company }
      else
        format.html { render :new }
        format.json { render json: @admin_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/companies/1
  # PATCH/PUT /admin/companies/1.json
  def update
    respond_to do |format|
      if @admin_company.update(admin_company_params)
        format.html { redirect_to @admin_company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_company }
      else
        format.html { render :edit }
        format.json { render json: @admin_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/companies/1
  # DELETE /admin/companies/1.json
  def destroy
    @admin_company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_company
      @admin_company = Admin::Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_company_params
      params.require(:admin_company).permit(:name, :enabled, :intro, :concept, :report, :salary)
    end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :set_admin_job, only: [:show, :edit, :update, :destroy]

  # GET /admin/jobs
  # GET /admin/jobs.json
  def index
    @admin_jobs = Admin::Job.includes(:company)
  end

  # GET /admin/jobs/1
  # GET /admin/jobs/1.json
  def show
  end

  # GET /admin/jobs/new
  def new
    @admin_job = Admin::Job.new
  end

  # GET /admin/jobs/1/edit
  def edit
  end

  # POST /admin/jobs
  # POST /admin/jobs.json
  def create
    @admin_job = Admin::Job.new(admin_job_params)

    respond_to do |format|
      if @admin_job.save
        format.html { redirect_to @admin_job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @admin_job }
      else
        format.html { render :new }
        format.json { render json: @admin_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/jobs/1
  # PATCH/PUT /admin/jobs/1.json
  def update
    respond_to do |format|
      if @admin_job.update(admin_job_params)
        format.html { redirect_to @admin_job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_job }
      else
        format.html { render :edit }
        format.json { render json: @admin_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/jobs/1
  # DELETE /admin/jobs/1.json
  def destroy
    @admin_job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_job
      @admin_job = Admin::Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_job_params
      params.require(:admin_job).permit(:admin_company_id, :name, :enabled, :intro, :condition, :welfare, :salary)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @companies = Admin::Company.enabled.order("RAND()").limit(5)
    @jobs = Admin::Job.enabled.order("RAND()").limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @companies = Admin::Company.enabled.order("RAND()").limit(5)
    @jobs = Admin::Job.enabled.order("RAND()").limit(10)
  end

  def companies
    @companies = Admin::Company.enabled
  end

  def jobs
    @jobs = Admin::Job.enabled
  end

  def company
    @company = Admin::Company.enabled.find_by_id(params[:id])
    @jobs = @company.jobs.enabled
  end

  def job
    @job = Admin::Job.enabled.find_by_id(params[:id])
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/companies/_form.html.erb
<%= form_with(model: admin_company, local: true) do |form| %>
  <% if admin_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_company.errors.count, "error") %> prohibited this admin_company from being saved:</h2>

      <ul>
      <% admin_company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :intro %>
    <%= form.text_area :intro %>
  </div>

  <div class="field">
    <%= form.label :concept %>
    <%= form.text_area :concept %>
  </div>

  <div class="field">
    <%= form.label :report %>
    <%= form.text_area :report %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_area :salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/companies/edit.html.erb
<h1>Editing Admin Company</h1>

<%= render 'form', admin_company: @admin_company %>

<%= link_to 'Show', @admin_company %> |
<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Intro</th>
      <th>Concept</th>
      <th>Report</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_companies.each do |admin_company| %>
      <tr>
        <td><%= admin_company.name %></td>
        <td><%= admin_company.intro %></td>
        <td><%= admin_company.concept %></td>
        <td><%= admin_company.report %></td>
        <td><%= admin_company.salary %></td>
        <td><%= link_to 'Show', admin_company %></td>
        <td><%= link_to 'Edit', edit_admin_company_path(admin_company) %></td>
        <td><%= link_to 'Destroy', admin_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Company', new_admin_company_path %>
<%= link_to 'Admin Home', admin_path %>

app/views/admin/companies/new.html.erb
<h1>New Admin Company</h1>

<%= render 'form', admin_company: @admin_company %>

<%= link_to 'Back', admin_companies_path %>

app/views/admin/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_company.name %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @admin_company.enabled %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @admin_company.intro %>
</p>

<p>
  <strong>Concept:</strong>
  <%= @admin_company.concept %>
</p>

<p>
  <strong>Report:</strong>
  <%= @admin_company.report %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @admin_company.salary %>
</p>

<%= link_to 'Edit', edit_admin_company_path(@admin_company) %> |
<%= link_to 'Back', admin_companies_path %>

app/views/admin/index.html.erb
<div>
  <h1>管理首頁<h1>
</div>

<span>公司列表</span>
<a href="<%= admin_companies_path %>">管理公司資訊</a>
<p>
<% @companies.each do |company| %>
  <a href="<%= admin_company_path(:id => company.id) %>">
      <span><%= company.name %></span>
  </a>
<% end %>
<p>
<span>職缺列表</span>
<a href="<%= admin_jobs_path %>">全部職缺</a>
<a href="<%= new_admin_job_path %>">新增職缺</a>
<p>
<% @jobs.each do |job| %> 
  <a href="<%= admin_job_path(:id => job.id) %>">
      <span><%= job.name %></span>
  </a>
<% end %>

app/views/admin/jobs/_form.html.erb
<%= form_with(model: admin_job, local: true) do |form| %>
  <% if admin_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_job.errors.count, "error") %> prohibited this admin_job from being saved:</h2>

      <ul>
      <% admin_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:admin_company_id].present? %>
    <%= form.hidden_field :admin_company_id, value: params[:admin_company_id] %>
  <% else %>
    <div class="field">
      <%= form.label :admin_company_id %>
      <%= form.select :admin_company_id, Admin::Company.all.map {|x| [x.name, x.id]} %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>

  <div class="field">
    <%= form.label :intro %>
    <%= form.text_area :intro %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_area :condition %>
  </div>

  <div class="field">
    <%= form.label :welfare %>
    <%= form.text_area :welfare %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_area :salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/jobs/edit.html.erb
<h1>Editing Admin Job</h1>

<%= render 'form', admin_job: @admin_job %>

<%= link_to 'Show', @admin_job %> |
<%= link_to 'Back', admin_jobs_path %>

app/views/admin/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Admin company</th>
      <th>Name</th>
      <th>Enabled</th>
      <th>Intro</th>
      <th>Condition</th>
      <th>Welfare</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_jobs.each do |admin_job| %>
      <tr>
        <td><%= admin_job.company.name %></td>
        <td><%= admin_job.name %></td>
        <td><%= admin_job.enabled %></td>
        <td><%= admin_job.intro %></td>
        <td><%= admin_job.condition %></td>
        <td><%= admin_job.welfare %></td>
        <td><%= admin_job.salary %></td>
        <td><%= link_to 'Show', admin_job %></td>
        <td><%= link_to 'Edit', edit_admin_job_path(admin_job) %></td>
        <td><%= link_to 'Destroy', admin_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Job', new_admin_job_path %>
<%= link_to 'Admin Home', admin_path %>

app/views/admin/jobs/new.html.erb
<h1>New Admin Job</h1>

<%= render 'form', admin_job: @admin_job %>

<%= link_to 'Back', admin_jobs_path %>

app/views/admin/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin company:</strong>
  <%= @admin_job.company.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_job.name %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @admin_job.enabled %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @admin_job.intro %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @admin_job.condition %>
</p>

<p>
  <strong>Welfare:</strong>
  <%= @admin_job.welfare %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @admin_job.salary %>
</p>

<%= link_to 'Edit', edit_admin_job_path(@admin_job) %> |
<%= link_to 'Back', admin_jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YBank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/companies.html.erb
<h1>公司列表</h1>
<% @companies.each do |company| %> 
  <a href="<%= company_path(:id => company.id) %>">
    <span><%= company.name %></span>
  </a>
<% end %>

app/views/page/company.html.erb
<h1><%= @company.name %></h1>
<h2>公司介紹</h2>
<%= simple_format @company.intro %>
<h2>公司理念</h2>
<%= simple_format @company.concept %>
<h2>媒體報導</h2>
<%= simple_format @company.report %>
<h2>薪資福利</h2>
<%= simple_format @company.salary %>
<h2>目前職缺</h2>
<% @jobs.each do |job| %> 
  <a href="<%= job_path(:id => job.id) %>">
    <span><%= job.name %></span>
  </a>
<% end %>

app/views/page/index.html.erb
<span>精選公司</span>
<a href="<%= companies_path %>">更多公司</a>
<p>
<% @companies.each do |company| %>
  <a href="<%= company_path(:id => company.id) %>">
      <span><%= company.name %></span>
  </a>
<% end %>
<p>
<span>精選職缺</span>
<a href="<%= jobs_path %>">更多職缺</a>
<p>
<% @jobs.each do |job| %> 
  <a href="<%= job_path(:id => job.id) %>">
      <span><%= job.name %></span>
  </a>
<% end %>

app/views/page/job.html.erb
<h1><%= @job.name %></h1>
<h2>工作內容</h2>
<%= simple_format @job.intro %>
<h2>條件要求</h2>
<%= simple_format @job.condition %>
<h2>公司福利</h2>
<%= simple_format @job.welfare %>
<h2>薪資範圍</h2>
<%= simple_format @job.salary %>
<a>應徵此職缺</a>

app/views/page/jobs.html.erb
<h1>職缺列表</h1>
<% @jobs.each do |job| %> 
  <a href="<%= job_path(:id => job.id) %>">
      <span><%= job.name %></span>
  </a>
<% end %>